function(orbit_apply_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive-)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endif()
endfunction()

function(orbit_apply_sanitizers target)
  if(ORBIT_ENABLE_ASAN)
    if(MSVC)
      message(WARNING "AddressSanitizer preset is limited on MSVC; use clang-cl or Linux CI.")
    else()
      target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    endif()
  endif()
endfunction()

function(orbit_apply_physics_fp target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /fp:precise)
  else()
    target_compile_options(${target} PRIVATE -fno-fast-math)
  endif()
endfunction()
